openapi: 3.0.3
info:
  title: Early Evidence Base API
  description: "Read-only API for the Early Evidence Base platform providing collections\
    \ of papers by reviewing service, automagic, and auto topics, as well as details\
    \ on papers by DOI."
  version: 2.0.0
servers:
- url: https://eeb.embo.org/api/v2
  description: Production server
- url: https://eeb-dev.embo.org/api/v2
  description: Development server
- url: http://localhost:5050/api/v2
  description: Local development server
tags:
- name: Reviewing Services
  description: Endpoints related to retrieving information about reviewing services.
- name: Paper Details
  description: Endpoints related to retrieving paper details.
paths:
  /reviewing_services/:
    get:
      tags:
      - Reviewing Services
      summary: Get information about available reviewing services.
      operationId: reviewing_services_get
      responses:
        "200":
          description: An array of reviewing services.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewingServiceDescription'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.reviewing_services_controller
  /papers/:
    get:
      tags:
      - Paper Details
      summary: "Get paginated collections of papers, optionally filtered by reviewing\
        \ service"
      operationId: papers_get
      parameters:
      - name: reviewedBy
        in: query
        description: "The IDs of the reviewing services for which papers are requested.\
          \ If specified, only papers that were reviewed by at least one of the specified\
          \ reviewing services are returned. Is combined with the query parameter\
          \ using a logical AND. If not specified, this filter is not applied."
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: query
        in: query
        description: "A search string to filter the results by. The search string\
          \ is matched against the paper DOI, title, abstract, and authors. The search\
          \ is case-insensitive and matches partial words (e.g. the search string\
          \ \"covid\" would match \"COVID-19\"). Is combined with the reviewedBy parameter\
          \ using a logical AND. If not specified, this filter is not applied."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: page
        in: query
        description: The page number of the results to retrieve. The first page is
          1.
        required: false
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          default: 1
      - name: perPage
        in: query
        description: The number of results to return per page.
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 1
          type: integer
          default: 10
      - name: sortBy
        in: query
        description: The field to sort the results by.
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/PaperSortBy'
      - name: sortOrder
        in: query
        description: The direction to sort the results in.
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/SortOrder'
      responses:
        "200":
          description: "An array of papers, filtered, sorted, and paged by the given\
            \ parameters."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request. The request parameters are invalid. The response
            body contains a JSON object with a detail property describing the error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: swagger_server.controllers.paper_details_controller
components:
  schemas:
    Paper:
      type: object
      properties:
        doi:
          type: string
          description: The DOI of the paper.
          format: doi
          example: 10.1101/2020.05.22.111161
        version:
          type: string
          description: The version of the paper.
          example: "1.0"
        source:
          type: string
          description: The source of the paper. Either "bioRxiv" or "medRxiv".
          example: bioRxiv
        journal:
          type: string
          description: The journal the paper was published in.
          example: bioRxiv
        title:
          type: string
        abstract:
          type: string
        journal_doi:
          type: string
          format: doi
          nullable: true
        published_journal_title:
          type: string
          nullable: true
        pub_date:
          type: string
          format: date-time
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        revdate:
          type: string
          format: date-time
          nullable: true
        entities:
          type: array
          items:
            type: string
        assays:
          type: array
          items:
            type: string
        main_topics:
          type: array
          items:
            type: array
            items:
              type: string
        highlighted_entities:
          type: array
          items:
            type: string
        slug:
          type: string
        reviewed_by:
          type: array
          items:
            type: string
      example:
        reviewed_by:
        - reviewed_by
        - reviewed_by
        assays:
        - assays
        - assays
        source: bioRxiv
        abstract: abstract
        title: title
        version: "1.0"
        published_journal_title: published_journal_title
        pub_date: 2000-01-23T04:56:07.000+00:00
        journal: bioRxiv
        main_topics:
        - - main_topics
          - main_topics
        - - main_topics
          - main_topics
        entities:
        - entities
        - entities
        highlighted_entities:
        - highlighted_entities
        - highlighted_entities
        revdate: 2000-01-23T04:56:07.000+00:00
        journal_doi: journal_doi
        slug: slug
        doi: 10.1101/2020.05.22.111161
        authors:
        - surname: surname
          corresp: corresp
          orcid: http://example.com/aeiou
          position_idx: 0
          given_names: given_names
        - surname: surname
          corresp: corresp
          orcid: http://example.com/aeiou
          position_idx: 0
          given_names: given_names
    Author:
      type: object
      properties:
        surname:
          type: string
        corresp:
          type: string
          nullable: true
        orcid:
          type: string
          format: uri
          nullable: true
        position_idx:
          type: integer
        given_names:
          type: string
      example:
        surname: surname
        corresp: corresp
        orcid: http://example.com/aeiou
        position_idx: 0
        given_names: given_names
    ReviewingServiceDescription:
      type: object
      properties:
        id:
          type: string
        peer_review_policy:
          type: string
          format: uri
        competing_interests:
          type: string
        opportunity_for_author_response:
          type: string
        reviewer_selected_by:
          type: string
        recommendation:
          type: string
        public_interaction:
          type: string
        review_coverage:
          type: string
        review_requested_by:
          type: string
        url:
          type: string
          format: uri
        reviewer_identity_known_to:
          type: string
      example:
        peer_review_policy: http://example.com/aeiou
        competing_interests: competing_interests
        opportunity_for_author_response: opportunity_for_author_response
        reviewer_selected_by: reviewer_selected_by
        recommendation: recommendation
        id: id
        public_interaction: public_interaction
        review_coverage: review_coverage
        review_requested_by: review_requested_by
        url: http://example.com/aeiou
        reviewer_identity_known_to: reviewer_identity_known_to
    PaperSortBy:
      type: string
      description: The field to sort the result by.
      default: preprint-date
      enum:
      - preprint-date
      - reviewing-date
    SortOrder:
      type: string
      description: The direction to sort the results in.
      default: desc
      enum:
      - asc
      - desc
    PagingInfo:
      type: object
      properties:
        first:
          type: string
          description: The URL of the first page of results.
          example: /api/v2/papers/?page=1
        prev:
          type: string
          description: The URL of the previous page of results. Null if the current
            page is the first page.
          nullable: true
          example: /api/v2/papers/?page=1
        current:
          type: string
          description: The URL of the current page of results.
          example: /api/v2/papers/?page=2
        next:
          type: string
          description: The URL of the next page of results. Null if the current page
            is the last page.
          nullable: true
          example: /api/v2/papers/?page=3
        last:
          type: string
          description: The URL of the last page of results.
          example: /api/v2/papers/?page=10
        currentPage:
          minimum: 1
          type: integer
          description: The page number of the current page of results.
          example: 2
        totalPages:
          minimum: 1
          type: integer
          description: The total number of pages of results.
          example: 17
        perPage:
          maximum: 100
          minimum: 1
          type: integer
          description: The number of results per page.
          example: 10
        totalItems:
          minimum: 0
          type: integer
          description: The total number of results.
          example: 195
        sortedBy:
          $ref: '#/components/schemas/PaperSortBy'
        sortedOrder:
          $ref: '#/components/schemas/SortOrder'
      example:
        next: /api/v2/papers/?page=3
        sortedBy: preprint-date
        current: /api/v2/papers/?page=2
        totalItems: 195
        perPage: 10
        last: /api/v2/papers/?page=10
        prev: /api/v2/papers/?page=1
        totalPages: 17
        currentPage: 2
        first: /api/v2/papers/?page=1
        sortedOrder: desc
    Error:
      type: object
      properties:
        detail:
          type: string
          description: A human-readable description of the error.
          example: "The sortBy parameter must be one of: preprint-date, reviewing-date"
        title:
          type: string
          description: A short description of the error.
          example: Bad Request
        status:
          type: integer
          description: The HTTP status code of the error.
          example: 400
        type:
          type: string
          description: A URI reference that identifies the problem type.
          example: about:blank
    inline_response_200:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Paper'
        paging:
          $ref: '#/components/schemas/PagingInfo'
      example:
        paging:
          next: /api/v2/papers/?page=3
          sortedBy: preprint-date
          current: /api/v2/papers/?page=2
          totalItems: 195
          perPage: 10
          last: /api/v2/papers/?page=10
          prev: /api/v2/papers/?page=1
          totalPages: 17
          currentPage: 2
          first: /api/v2/papers/?page=1
          sortedOrder: desc
        items:
        - reviewed_by:
          - reviewed_by
          - reviewed_by
          assays:
          - assays
          - assays
          source: bioRxiv
          abstract: abstract
          title: title
          version: "1.0"
          published_journal_title: published_journal_title
          pub_date: 2000-01-23T04:56:07.000+00:00
          journal: bioRxiv
          main_topics:
          - - main_topics
            - main_topics
          - - main_topics
            - main_topics
          entities:
          - entities
          - entities
          highlighted_entities:
          - highlighted_entities
          - highlighted_entities
          revdate: 2000-01-23T04:56:07.000+00:00
          journal_doi: journal_doi
          slug: slug
          doi: 10.1101/2020.05.22.111161
          authors:
          - surname: surname
            corresp: corresp
            orcid: http://example.com/aeiou
            position_idx: 0
            given_names: given_names
          - surname: surname
            corresp: corresp
            orcid: http://example.com/aeiou
            position_idx: 0
            given_names: given_names
        - reviewed_by:
          - reviewed_by
          - reviewed_by
          assays:
          - assays
          - assays
          source: bioRxiv
          abstract: abstract
          title: title
          version: "1.0"
          published_journal_title: published_journal_title
          pub_date: 2000-01-23T04:56:07.000+00:00
          journal: bioRxiv
          main_topics:
          - - main_topics
            - main_topics
          - - main_topics
            - main_topics
          entities:
          - entities
          - entities
          highlighted_entities:
          - highlighted_entities
          - highlighted_entities
          revdate: 2000-01-23T04:56:07.000+00:00
          journal_doi: journal_doi
          slug: slug
          doi: 10.1101/2020.05.22.111161
          authors:
          - surname: surname
            corresp: corresp
            orcid: http://example.com/aeiou
            position_idx: 0
            given_names: given_names
          - surname: surname
            corresp: corresp
            orcid: http://example.com/aeiou
            position_idx: 0
            given_names: given_names

